Traceback (most recent call last):
  File "c:\Users\kagaya\OneDrive\Artificial Intelligence\demo\demoAI.py", line 367, in <module>
    AIDEMO.GameStart()
  File "c:\Users\kagaya\OneDrive\Artificial Intelligence\demo\demoAI.py", line 316, in GameStart
    opponentMove = self.board.parse_san(AnothersideInput)
  File "C:\Users\kagaya\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\__init__.py", line 2596, in parse_san
    raise ValueError("illegal san: {0} in {1}".format(repr(san), self.fen()))
ValueError: illegal san: 'h7' in rnbqkbnr/pppppppp/8/8/7P/8/PPPPPPP1/RNBQKBNR b KQkq - 0 1
